/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSkill {
  'skillId' : string,
  'skillName' : string,
  'isCustom' : boolean,
}
export type AppId = string;
export type ApplicationStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface AuditLog {
  'resource' : string,
  'action' : string,
  'logId' : LogId,
  'timestamp' : Timestamp,
  'details' : string,
  'adminId' : UserId,
}
export type CallerRole = { 'Customer' : null } |
  { 'CollegeAdmin' : null } |
  { 'DatabaseAdmin' : null };
export interface CleanupFilter {
  'olderThanDays' : [] | [bigint],
  'callerRole' : CallerRole,
  'collegeIdFilter' : [] | [string],
  'statusFilter' : [] | [Array<OrderStatus>],
}
export interface CleanupLog {
  'cleanupType' : string,
  'logId' : LogId,
  'performedAt' : Timestamp,
  'performedBy' : UserId,
  'recordsRemoved' : bigint,
}
export interface CleanupResult { 'deletedCount' : bigint, 'message' : string }
export interface College {
  'adminIds' : Array<UserId>,
  'collegeCode' : string,
  'collegeName' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'adminCount' : bigint,
  'collegeId' : CollegeId,
  'commissionPercent' : bigint,
  'adminEmail' : string,
  'contactPhone' : string,
}
export interface CollegeAnalytics {
  'totalOrders' : bigint,
  'collegeName' : string,
  'collegeId' : string,
  'activeOrders' : bigint,
  'totalRevenue' : bigint,
}
export type CollegeId = string;
export interface CollegePricing {
  'urgencyCharge' : bigint,
  'collegeName' : string,
  'hardCopy' : bigint,
  'otherBase' : bigint,
  'softCopy' : bigint,
  'notesWriting' : bigint,
  'recordWriting' : bigint,
}
export interface DashboardSummary {
  'writerStats' : Array<WriterAnalytics>,
  'collegeStats' : Array<CollegeAnalytics>,
  'totalUsers' : bigint,
  'orderStats' : OrderAnalytics,
  'totalColleges' : bigint,
}
export type DeliveryStatus = { 'Delivered' : null } |
  { 'NotDelivered' : null };
export type LockStatus = { 'Unlocked' : null } |
  { 'Locked' : null };
export type LogId = string;
export interface MaintenanceLog {
  'enabledTime' : bigint,
  'enabledBy' : string,
  'disabledTime' : [] | [bigint],
  'reason' : string,
  'affectedUsersCount' : bigint,
}
export interface Message {
  'isDeleted' : boolean,
  'messageId' : MessageId,
  'text' : string,
  'fileKeys' : Array<string>,
  'isRead' : boolean,
  'orderId' : OrderId,
  'timestamp' : Timestamp,
  'senderName' : string,
  'senderRole' : UserRole,
  'senderId' : UserId,
}
export type MessageId = string;
export type NotifId = string;
export interface Notification {
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'notifId' : NotifId,
  'isRead' : boolean,
  'message' : string,
  'relatedId' : [] | [string],
}
export type NotificationType = { 'orderAccepted' : null } |
  { 'deliveryUploaded' : null } |
  { 'newOrder' : null } |
  { 'orderCompleted' : null } |
  { 'paymentReceived' : null } |
  { 'general' : null } |
  { 'orderReassigned' : null } |
  { 'revisionRequested' : null };
export interface Order {
  'status' : OrderStatus,
  'serviceType' : ServiceType,
  'acceptedByAdminName' : [] | [string],
  'subject' : string,
  'customerPhone' : [] | [string],
  'urgentFlag' : boolean,
  'urgencyCharge' : bigint,
  'revenueRecorded' : boolean,
  'materialChoice' : [] | [string],
  'createdAt' : Timestamp,
  'materialChargeAmount' : bigint,
  'acceptedByAdminId' : [] | [string],
  'revisionCount' : bigint,
  'deliveryStatus' : DeliveryStatus,
  'description' : string,
  'fileKeys' : Array<string>,
  'deadline' : Timestamp,
  'orderId' : OrderId,
  'updatedAt' : Timestamp,
  'assignmentLockStatus' : LockStatus,
  'adminMessages' : Array<string>,
  'customCollege' : [] | [string],
  'paperChargeAmount' : bigint,
  'submissionFiles' : Array<string>,
  'customerId' : UserId,
  'adminId' : [] | [UserId],
  'paymentSettlementStatus' : PaymentSettlementStatus,
  'acceptedAt' : [] | [Timestamp],
  'totalPrice' : bigint,
  'basePrice' : bigint,
  'college' : string,
  'pageCount' : bigint,
}
export interface OrderAnalytics {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'completedOrders' : bigint,
  'totalRevenue' : bigint,
  'deliveredOrders' : bigint,
}
export type OrderId = string;
export type OrderStatus = { 'ActiveReadyToStart' : null } |
  { 'Review' : null } |
  { 'Closed' : null } |
  { 'PendingPaymentVerification' : null } |
  { 'Delivered' : null } |
  { 'Correction' : null } |
  { 'InProgress' : null } |
  { 'Assigned' : null } |
  { 'Completed' : null };
export interface PaperChargeConfig {
  'serviceType' : ServiceType,
  'paperChargePerPage' : bigint,
  'paperChargeEnabled' : boolean,
}
export interface PaperChargeUpdate {
  'serviceType' : ServiceType,
  'paperChargePerPage' : bigint,
  'paperChargeEnabled' : boolean,
}
export interface Payment {
  'status' : PaymentStatus,
  'paymentMethod' : string,
  'expiredAt' : bigint,
  'failureReason' : [] | [string],
  'transactionState' : TransactionState,
  'screenshotKey' : [] | [string],
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'attemptCount' : bigint,
  'updatedAt' : bigint,
  'collegeId' : string,
  'proofFileKey' : [] | [string],
  'paymentId' : PaymentId,
  'timestamp' : bigint,
  'deviceInfo' : [] | [string],
  'customerId' : UserId,
  'adminId' : [] | [string],
  'amount' : bigint,
  'verifiedAt' : [] | [Timestamp],
  'verifiedBy' : [] | [string],
  'ipAddress' : [] | [string],
  'screenshotFileKey' : string,
  'transactionId' : string,
}
export interface PaymentAuditLog {
  'action' : string,
  'actorId' : string,
  'orderId' : [] | [string],
  'logId' : string,
  'timestamp' : bigint,
  'details' : [] | [string],
  'deviceInfo' : [] | [string],
  'amount' : [] | [bigint],
  'ipAddress' : [] | [string],
  'transactionId' : [] | [string],
}
export type PaymentId = string;
export interface PaymentLog {
  'orderId' : string,
  'logId' : string,
  'paymentId' : string,
  'timestamp' : bigint,
  'customerId' : UserId,
  'adminRemarks' : string,
  'reason' : string,
}
export interface PaymentSettings {
  'hasQrBlob' : boolean,
  'upiId' : string,
  'qrCodeKey' : string,
  'showQrToUsers' : boolean,
}
export type PaymentSettlementStatus = { 'Settled' : null } |
  { 'Pending' : null };
export type PaymentStatus = { 'Rejected' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface PaymentVerification {
  'reviewNotes' : [] | [string],
  'screenshotUrl' : [] | [string],
  'submittedAt' : bigint,
  'reviewedBy' : [] | [string],
  'verificationId' : string,
  'reviewTimestamp' : [] | [bigint],
  'verificationStatus' : string,
  'transactionId' : string,
}
export interface ReassignmentLog {
  'newAdminId' : UserId,
  'previousAdminName' : string,
  'reassignedAt' : Timestamp,
  'reassignedBy' : UserId,
  'orderId' : OrderId,
  'logId' : LogId,
  'previousAdminId' : UserId,
  'newAdminName' : string,
  'reason' : string,
}
export interface ServicePriceEntry {
  'serviceType' : ServiceType,
  'urgencyCharge' : bigint,
  'paperChargePerPage' : bigint,
  'paperChargeEnabled' : boolean,
  'basePrice' : bigint,
}
export type ServiceType = { 'HardCopy' : null } |
  { 'RecordWriting' : null } |
  { 'SoftCopy' : null } |
  { 'NotesWriting' : null };
export interface SystemSettings {
  'websiteName' : string,
  'qrCodeBlob' : [] | [Uint8Array],
  'maintenanceMessage' : string,
  'maintenanceEnabledAt' : [] | [bigint],
  'servicePrices' : Array<ServicePriceEntry>,
  'emergencySupportEmail' : string,
  'whatsappLink' : string,
  'supportFormUrl' : string,
  'maintenanceLogs' : Array<MaintenanceLog>,
  'maintenanceMode' : boolean,
  'notebookPrice' : bigint,
  'requirePaymentBeforeSubmission' : boolean,
  'themeConfig' : ThemeConfig,
  'recordBookPrice' : bigint,
  'whatsappNumber' : string,
  'supportEmail' : string,
  'upiId' : string,
  'qrCodeKey' : string,
  'databaseAdminSharePercent' : bigint,
  'maintenanceEndTime' : [] | [string],
  'showQrToUsers' : boolean,
  'allowNewOrders' : boolean,
  'settingsId' : string,
  'adminSharePercent' : bigint,
}
export interface ThemeConfig {
  'primaryColor' : string,
  'sidebarWidth' : bigint,
  'accentColor' : string,
  'fontFamily' : string,
  'sidebarColor' : string,
}
export type Timestamp = bigint;
export type TransactionState = { 'Failed' : null } |
  { 'Refunded' : null } |
  { 'Cancelled' : null } |
  { 'Processing' : null } |
  { 'Created' : null } |
  { 'Verified' : null } |
  { 'Pending' : null };
export interface User {
  'dateOfBirth' : [] | [string],
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'collegeId' : [] | [string],
  'passwordHash' : [] | [string],
  'lastLogin' : Timestamp,
  'skills' : Array<AdminSkill>,
  'registeredCollegeId' : [] | [string],
  'mustChangePassword' : boolean,
}
export type UserId = Principal;
export type UserRole = { 'customer' : null } |
  { 'databaseAdmin' : null } |
  { 'collegeAdmin' : null };
export interface WriterAnalytics {
  'writerId' : Principal,
  'completedOrders' : bigint,
  'assignedOrders' : bigint,
  'writerName' : string,
}
export interface WriterApplication {
  'bio' : string,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'applicantName' : string,
  'appId' : AppId,
  'collegeName' : string,
  'handwritingUrl' : string,
  'reviewNote' : string,
  'reviewedBy' : [] | [string],
  'email' : string,
  'updatedAt' : bigint,
  'expertise' : Array<string>,
  'phone' : string,
  'resumeKey' : [] | [string],
  'resumeUrl' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'acceptOrder' : ActorMethod<[OrderId, string], boolean>,
  'addAdminToCollege' : ActorMethod<[CollegeId, UserId], boolean>,
  'approveApplication' : ActorMethod<
    [AppId, string],
    { 'ok' : WriterApplication } |
      { 'err' : string }
  >,
  'assignUserRole' : ActorMethod<[UserId, UserRole], boolean>,
  'changePassword' : ActorMethod<[string, string], boolean>,
  'cleanOldAuditLogs' : ActorMethod<[], bigint>,
  'cleanOldNotifications' : ActorMethod<[], bigint>,
  'cleanOldOrders' : ActorMethod<[], bigint>,
  'countTotalUsers' : ActorMethod<[], bigint>,
  'createCollege' : ActorMethod<[string, string, string], College>,
  'createNotification' : ActorMethod<
    [UserId, NotificationType, string, [] | [string]],
    Notification
  >,
  'deactivateUser' : ActorMethod<[UserId], boolean>,
  'deleteApplication' : ActorMethod<
    [AppId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteMessage' : ActorMethod<
    [MessageId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'dryRunSmartCleanup' : ActorMethod<[CleanupFilter], CleanupResult>,
  'estimatePrice' : ActorMethod<
    [ServiceType, boolean, bigint],
    {
      'total' : bigint,
      'urgency' : bigint,
      'base' : bigint,
      'paperCharge' : bigint,
    }
  >,
  'forceReassignOrder' : ActorMethod<
    [OrderId, UserId, string, string],
    boolean
  >,
  'generateAdminIdPreview' : ActorMethod<[string, bigint], string>,
  'getAdminAccount' : ActorMethod<[string], [] | [User]>,
  'getAdminOrders' : ActorMethod<[], Array<Order>>,
  'getAdminRevenueStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getAllCollegesPricing' : ActorMethod<[], Array<CollegePricing>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getApplication' : ActorMethod<[AppId], [] | [WriterApplication]>,
  'getCollege' : ActorMethod<[CollegeId], [] | [College]>,
  'getCollegePricing' : ActorMethod<[string], [] | [CollegePricing]>,
  'getCollegeRevenueStats' : ActorMethod<[], Array<[string, bigint]>>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getMaintenanceLogs' : ActorMethod<[], Array<MaintenanceLog>>,
  'getMaterialPrices' : ActorMethod<
    [],
    { 'notebookPrice' : bigint, 'recordBookPrice' : bigint }
  >,
  'getMyAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getMyCollegePaymentVerifications' : ActorMethod<
    [],
    Array<PaymentVerification>
  >,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPayments' : ActorMethod<[], Array<Payment>>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getMyUnreadCount' : ActorMethod<[], bigint>,
  'getOrCreateSessionToken' : ActorMethod<[], string>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrderMessages' : ActorMethod<[OrderId], Array<Message>>,
  'getOrderPayments' : ActorMethod<[OrderId], Array<Payment>>,
  'getOrdersByCollege' : ActorMethod<[string], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<
    [],
    Array<{ 'status' : string, 'count' : bigint }>
  >,
  'getPaperChargeConfig' : ActorMethod<[ServiceType], [] | [PaperChargeConfig]>,
  'getPaymentAuditLogs' : ActorMethod<[bigint], Array<PaymentAuditLog>>,
  'getPaymentLogs' : ActorMethod<[], Array<PaymentLog>>,
  'getPaymentQrBlob' : ActorMethod<[], [] | [Uint8Array]>,
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  'getPaymentVerification' : ActorMethod<[string], [] | [PaymentVerification]>,
  'getPaymentVerifications' : ActorMethod<[], Array<PaymentVerification>>,
  'getPaymentsByOrder' : ActorMethod<[string], Array<Payment>>,
  'getRevenueByCollege' : ActorMethod<
    [],
    Array<{ 'revenue' : bigint, 'college' : string }>
  >,
  'getSystemSettings' : ActorMethod<[], SystemSettings>,
  'getTotalRevenue' : ActorMethod<[], bigint>,
  'getTransactionDashboardStats' : ActorMethod<
    [],
    {
      'recentTransactions' : Array<Payment>,
      'failedPayments' : bigint,
      'totalRevenue' : bigint,
      'successfulTransactions' : bigint,
      'pendingVerifications' : bigint,
    }
  >,
  'getUnreadCount' : ActorMethod<[OrderId], bigint>,
  'getUserByEmail' : ActorMethod<[string], [] | [User]>,
  'getUserById' : ActorMethod<[UserId], [] | [User]>,
  'getUserBySessionToken' : ActorMethod<[string], [] | [User]>,
  'getWriterApplication' : ActorMethod<[AppId], [] | [WriterApplication]>,
  'listAllReassignmentLogs' : ActorMethod<[], Array<ReassignmentLog>>,
  'listApplications' : ActorMethod<[], Array<WriterApplication>>,
  'listCleanupLogs' : ActorMethod<[], Array<CleanupLog>>,
  'listCollegeAdmins' : ActorMethod<[CollegeId], Array<UserId>>,
  'listColleges' : ActorMethod<[], Array<College>>,
  'listPaperChargeConfigs' : ActorMethod<[], Array<PaperChargeConfig>>,
  'listReassignmentLogs' : ActorMethod<[OrderId], Array<ReassignmentLog>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'listWriterApplications' : ActorMethod<[], Array<WriterApplication>>,
  'logAction' : ActorMethod<[string, string, string], AuditLog>,
  'loginAsCustomer' : ActorMethod<[string], [] | [User]>,
  'markMessageRead' : ActorMethod<[MessageId], boolean>,
  'markNotificationRead' : ActorMethod<[NotifId], boolean>,
  'placeOrder' : ActorMethod<
    [
      string,
      ServiceType,
      string,
      Timestamp,
      string,
      boolean,
      bigint,
      Array<string>,
      [] | [string],
      bigint,
    ],
    Order
  >,
  'pollPaymentStatus' : ActorMethod<
    [string],
    {
      'status' : string,
      'expiredAt' : bigint,
      'failureReason' : [] | [string],
      'transactionState' : string,
      'verifiedAt' : [] | [bigint],
      'transactionId' : string,
    }
  >,
  'reassignOrder' : ActorMethod<
    [OrderId, UserId, string, string],
    ReassignmentLog
  >,
  'registerUser' : ActorMethod<
    [string, string, UserRole, [] | [string], [] | [string]],
    UserId
  >,
  'rejectApplication' : ActorMethod<
    [AppId, string],
    { 'ok' : WriterApplication } |
      { 'err' : string }
  >,
  'rejectPayment' : ActorMethod<[PaymentId], boolean>,
  'removeAdminFromCollege' : ActorMethod<[CollegeId, UserId], boolean>,
  'runFullCleanup' : ActorMethod<
    [],
    {
      'logsRemoved' : bigint,
      'ordersRemoved' : bigint,
      'notifsRemoved' : bigint,
    }
  >,
  'sendMessage' : ActorMethod<[OrderId, string, Array<string>], Message>,
  'setAllowNewOrders' : ActorMethod<[boolean], undefined>,
  'setCollegePricing' : ActorMethod<[CollegePricing], undefined>,
  'setCustomerCollege' : ActorMethod<[UserId, string], boolean>,
  'setMaintenanceEndTime' : ActorMethod<[[] | [string]], undefined>,
  'setMaintenanceMessage' : ActorMethod<[string], undefined>,
  'setMaintenanceMode' : ActorMethod<[boolean], undefined>,
  'setMaintenanceReason' : ActorMethod<[string], undefined>,
  'setMaterialPrices' : ActorMethod<[bigint, bigint], undefined>,
  'setPaperChargeConfig' : ActorMethod<[PaperChargeUpdate], boolean>,
  'setPaperChargeConfigs' : ActorMethod<[Array<PaperChargeUpdate>], boolean>,
  'setSupportEmail' : ActorMethod<[string], undefined>,
  'setSupportFormUrl' : ActorMethod<[string], undefined>,
  'setWhatsappLink' : ActorMethod<[string], undefined>,
  'setWhatsappNumber' : ActorMethod<[string], undefined>,
  'settleOrderPayment' : ActorMethod<[OrderId], boolean>,
  'smartCleanup' : ActorMethod<[CleanupFilter], CleanupResult>,
  'submitPayment' : ActorMethod<[OrderId], Payment>,
  'submitPaymentRequest' : ActorMethod<
    [OrderId, string],
    { 'ok' : Payment } |
      { 'err' : string }
  >,
  'submitWriterApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      [] | [string],
      string,
    ],
    WriterApplication
  >,
  'updateAdminSkills' : ActorMethod<[Array<AdminSkill>], boolean>,
  'updateApplicationStatus' : ActorMethod<[AppId, ApplicationStatus], boolean>,
  'updateCollege' : ActorMethod<
    [CollegeId, string, string, string, bigint],
    boolean
  >,
  'updateLastLogin' : ActorMethod<[], undefined>,
  'updateMaintenanceContacts' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
  'updatePaymentSettings' : ActorMethod<[string, string, boolean], undefined>,
  'updateProfile' : ActorMethod<[string, string], boolean>,
  'updateQrCode' : ActorMethod<[string], undefined>,
  'updateServicePricing' : ActorMethod<[Array<ServicePriceEntry>], undefined>,
  'updateSharePercents' : ActorMethod<[bigint, bigint], undefined>,
  'updateSystemSettings' : ActorMethod<[SystemSettings], SystemSettings>,
  'updateTheme' : ActorMethod<[ThemeConfig], undefined>,
  'updateUpiId' : ActorMethod<[string], undefined>,
  'updateWebsiteName' : ActorMethod<[string], undefined>,
  'uploadDelivery' : ActorMethod<[OrderId, Array<string>], boolean>,
  'uploadPaymentQr' : ActorMethod<[Uint8Array], string>,
  'uploadPaymentScreenshot' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'verifyPayment' : ActorMethod<[PaymentId], boolean>,
  'verifyPaymentManually' : ActorMethod<
    [string, boolean, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];