/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const OrderId = IDL.Text;
export const CollegeId = IDL.Text;
export const UserId = IDL.Principal;
export const AppId = IDL.Text;
export const ApplicationStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const WriterApplication = IDL.Record({
  'bio' : IDL.Text,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'applicantName' : IDL.Text,
  'appId' : AppId,
  'collegeName' : IDL.Text,
  'handwritingUrl' : IDL.Text,
  'reviewNote' : IDL.Text,
  'reviewedBy' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'expertise' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
  'resumeKey' : IDL.Opt(IDL.Text),
  'resumeUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'customer' : IDL.Null,
  'databaseAdmin' : IDL.Null,
  'collegeAdmin' : IDL.Null,
});
export const College = IDL.Record({
  'adminIds' : IDL.Vec(UserId),
  'collegeCode' : IDL.Text,
  'collegeName' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'adminCount' : IDL.Nat,
  'collegeId' : CollegeId,
  'commissionPercent' : IDL.Nat,
  'adminEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'orderAccepted' : IDL.Null,
  'deliveryUploaded' : IDL.Null,
  'newOrder' : IDL.Null,
  'orderCompleted' : IDL.Null,
  'paymentReceived' : IDL.Null,
  'general' : IDL.Null,
  'orderReassigned' : IDL.Null,
  'revisionRequested' : IDL.Null,
});
export const NotifId = IDL.Text;
export const Notification = IDL.Record({
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'notifId' : NotifId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Text),
});
export const MessageId = IDL.Text;
export const CallerRole = IDL.Variant({
  'Customer' : IDL.Null,
  'CollegeAdmin' : IDL.Null,
  'DatabaseAdmin' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'ActiveReadyToStart' : IDL.Null,
  'Review' : IDL.Null,
  'Closed' : IDL.Null,
  'PendingPaymentVerification' : IDL.Null,
  'Delivered' : IDL.Null,
  'Correction' : IDL.Null,
  'InProgress' : IDL.Null,
  'Assigned' : IDL.Null,
  'Completed' : IDL.Null,
});
export const CleanupFilter = IDL.Record({
  'olderThanDays' : IDL.Opt(IDL.Nat),
  'callerRole' : CallerRole,
  'collegeIdFilter' : IDL.Opt(IDL.Text),
  'statusFilter' : IDL.Opt(IDL.Vec(OrderStatus)),
});
export const CleanupResult = IDL.Record({
  'deletedCount' : IDL.Nat,
  'message' : IDL.Text,
});
export const ServiceType = IDL.Variant({
  'HardCopy' : IDL.Null,
  'RecordWriting' : IDL.Null,
  'SoftCopy' : IDL.Null,
  'NotesWriting' : IDL.Null,
});
export const AdminSkill = IDL.Record({
  'skillId' : IDL.Text,
  'skillName' : IDL.Text,
  'isCustom' : IDL.Bool,
});
export const User = IDL.Record({
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'collegeId' : IDL.Opt(IDL.Text),
  'passwordHash' : IDL.Opt(IDL.Text),
  'lastLogin' : Timestamp,
  'skills' : IDL.Vec(AdminSkill),
  'registeredCollegeId' : IDL.Opt(IDL.Text),
  'mustChangePassword' : IDL.Bool,
});
export const DeliveryStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'NotDelivered' : IDL.Null,
});
export const LockStatus = IDL.Variant({
  'Unlocked' : IDL.Null,
  'Locked' : IDL.Null,
});
export const PaymentSettlementStatus = IDL.Variant({
  'Settled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : OrderStatus,
  'serviceType' : ServiceType,
  'acceptedByAdminName' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'customerPhone' : IDL.Opt(IDL.Text),
  'urgentFlag' : IDL.Bool,
  'urgencyCharge' : IDL.Nat,
  'revenueRecorded' : IDL.Bool,
  'materialChoice' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'materialChargeAmount' : IDL.Nat,
  'acceptedByAdminId' : IDL.Opt(IDL.Text),
  'revisionCount' : IDL.Nat,
  'deliveryStatus' : DeliveryStatus,
  'description' : IDL.Text,
  'fileKeys' : IDL.Vec(IDL.Text),
  'deadline' : Timestamp,
  'orderId' : OrderId,
  'updatedAt' : Timestamp,
  'assignmentLockStatus' : LockStatus,
  'adminMessages' : IDL.Vec(IDL.Text),
  'customCollege' : IDL.Opt(IDL.Text),
  'paperChargeAmount' : IDL.Nat,
  'submissionFiles' : IDL.Vec(IDL.Text),
  'customerId' : UserId,
  'adminId' : IDL.Opt(UserId),
  'paymentSettlementStatus' : PaymentSettlementStatus,
  'acceptedAt' : IDL.Opt(Timestamp),
  'totalPrice' : IDL.Nat,
  'basePrice' : IDL.Nat,
  'college' : IDL.Text,
  'pageCount' : IDL.Nat,
});
export const LogId = IDL.Text;
export const AuditLog = IDL.Record({
  'resource' : IDL.Text,
  'action' : IDL.Text,
  'logId' : LogId,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'adminId' : UserId,
});
export const CollegePricing = IDL.Record({
  'urgencyCharge' : IDL.Nat,
  'collegeName' : IDL.Text,
  'hardCopy' : IDL.Nat,
  'otherBase' : IDL.Nat,
  'softCopy' : IDL.Nat,
  'notesWriting' : IDL.Nat,
  'recordWriting' : IDL.Nat,
});
export const WriterAnalytics = IDL.Record({
  'writerId' : IDL.Principal,
  'completedOrders' : IDL.Nat,
  'assignedOrders' : IDL.Nat,
  'writerName' : IDL.Text,
});
export const CollegeAnalytics = IDL.Record({
  'totalOrders' : IDL.Nat,
  'collegeName' : IDL.Text,
  'collegeId' : IDL.Text,
  'activeOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const OrderAnalytics = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'completedOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'deliveredOrders' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'writerStats' : IDL.Vec(WriterAnalytics),
  'collegeStats' : IDL.Vec(CollegeAnalytics),
  'totalUsers' : IDL.Nat,
  'orderStats' : OrderAnalytics,
  'totalColleges' : IDL.Nat,
});
export const MaintenanceLog = IDL.Record({
  'enabledTime' : IDL.Int,
  'enabledBy' : IDL.Text,
  'disabledTime' : IDL.Opt(IDL.Int),
  'reason' : IDL.Text,
  'affectedUsersCount' : IDL.Nat,
});
export const PaymentVerification = IDL.Record({
  'reviewNotes' : IDL.Opt(IDL.Text),
  'screenshotUrl' : IDL.Opt(IDL.Text),
  'submittedAt' : IDL.Int,
  'reviewedBy' : IDL.Opt(IDL.Text),
  'verificationId' : IDL.Text,
  'reviewTimestamp' : IDL.Opt(IDL.Int),
  'verificationStatus' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TransactionState = IDL.Variant({
  'Failed' : IDL.Null,
  'Refunded' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Processing' : IDL.Null,
  'Created' : IDL.Null,
  'Verified' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentId = IDL.Text;
export const Payment = IDL.Record({
  'status' : PaymentStatus,
  'paymentMethod' : IDL.Text,
  'expiredAt' : IDL.Int,
  'failureReason' : IDL.Opt(IDL.Text),
  'transactionState' : TransactionState,
  'screenshotKey' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'attemptCount' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'collegeId' : IDL.Text,
  'proofFileKey' : IDL.Opt(IDL.Text),
  'paymentId' : PaymentId,
  'timestamp' : IDL.Int,
  'deviceInfo' : IDL.Opt(IDL.Text),
  'customerId' : UserId,
  'adminId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'verifiedAt' : IDL.Opt(Timestamp),
  'verifiedBy' : IDL.Opt(IDL.Text),
  'ipAddress' : IDL.Opt(IDL.Text),
  'screenshotFileKey' : IDL.Text,
  'transactionId' : IDL.Text,
});
export const Message = IDL.Record({
  'isDeleted' : IDL.Bool,
  'messageId' : MessageId,
  'text' : IDL.Text,
  'fileKeys' : IDL.Vec(IDL.Text),
  'isRead' : IDL.Bool,
  'orderId' : OrderId,
  'timestamp' : Timestamp,
  'senderName' : IDL.Text,
  'senderRole' : UserRole,
  'senderId' : UserId,
});
export const PaperChargeConfig = IDL.Record({
  'serviceType' : ServiceType,
  'paperChargePerPage' : IDL.Nat,
  'paperChargeEnabled' : IDL.Bool,
});
export const PaymentAuditLog = IDL.Record({
  'action' : IDL.Text,
  'actorId' : IDL.Text,
  'orderId' : IDL.Opt(IDL.Text),
  'logId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Opt(IDL.Text),
  'deviceInfo' : IDL.Opt(IDL.Text),
  'amount' : IDL.Opt(IDL.Nat),
  'ipAddress' : IDL.Opt(IDL.Text),
  'transactionId' : IDL.Opt(IDL.Text),
});
export const PaymentLog = IDL.Record({
  'orderId' : IDL.Text,
  'logId' : IDL.Text,
  'paymentId' : IDL.Text,
  'timestamp' : IDL.Int,
  'customerId' : UserId,
  'adminRemarks' : IDL.Text,
  'reason' : IDL.Text,
});
export const PaymentSettings = IDL.Record({
  'hasQrBlob' : IDL.Bool,
  'upiId' : IDL.Text,
  'qrCodeKey' : IDL.Text,
  'showQrToUsers' : IDL.Bool,
});
export const ServicePriceEntry = IDL.Record({
  'serviceType' : ServiceType,
  'urgencyCharge' : IDL.Nat,
  'paperChargePerPage' : IDL.Nat,
  'paperChargeEnabled' : IDL.Bool,
  'basePrice' : IDL.Nat,
});
export const ThemeConfig = IDL.Record({
  'primaryColor' : IDL.Text,
  'sidebarWidth' : IDL.Nat,
  'accentColor' : IDL.Text,
  'fontFamily' : IDL.Text,
  'sidebarColor' : IDL.Text,
});
export const SystemSettings = IDL.Record({
  'websiteName' : IDL.Text,
  'qrCodeBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'maintenanceMessage' : IDL.Text,
  'maintenanceEnabledAt' : IDL.Opt(IDL.Int),
  'servicePrices' : IDL.Vec(ServicePriceEntry),
  'emergencySupportEmail' : IDL.Text,
  'whatsappLink' : IDL.Text,
  'supportFormUrl' : IDL.Text,
  'maintenanceLogs' : IDL.Vec(MaintenanceLog),
  'maintenanceMode' : IDL.Bool,
  'notebookPrice' : IDL.Nat,
  'requirePaymentBeforeSubmission' : IDL.Bool,
  'themeConfig' : ThemeConfig,
  'recordBookPrice' : IDL.Nat,
  'whatsappNumber' : IDL.Text,
  'supportEmail' : IDL.Text,
  'upiId' : IDL.Text,
  'qrCodeKey' : IDL.Text,
  'databaseAdminSharePercent' : IDL.Nat,
  'maintenanceEndTime' : IDL.Opt(IDL.Text),
  'showQrToUsers' : IDL.Bool,
  'allowNewOrders' : IDL.Bool,
  'settingsId' : IDL.Text,
  'adminSharePercent' : IDL.Nat,
});
export const ReassignmentLog = IDL.Record({
  'newAdminId' : UserId,
  'previousAdminName' : IDL.Text,
  'reassignedAt' : Timestamp,
  'reassignedBy' : UserId,
  'orderId' : OrderId,
  'logId' : LogId,
  'previousAdminId' : UserId,
  'newAdminName' : IDL.Text,
  'reason' : IDL.Text,
});
export const CleanupLog = IDL.Record({
  'cleanupType' : IDL.Text,
  'logId' : LogId,
  'performedAt' : Timestamp,
  'performedBy' : UserId,
  'recordsRemoved' : IDL.Nat,
});
export const PaperChargeUpdate = IDL.Record({
  'serviceType' : ServiceType,
  'paperChargePerPage' : IDL.Nat,
  'paperChargeEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'acceptOrder' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
  'addAdminToCollege' : IDL.Func([CollegeId, UserId], [IDL.Bool], []),
  'approveApplication' : IDL.Func(
      [AppId, IDL.Text],
      [IDL.Variant({ 'ok' : WriterApplication, 'err' : IDL.Text })],
      [],
    ),
  'assignUserRole' : IDL.Func([UserId, UserRole], [IDL.Bool], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'cleanOldAuditLogs' : IDL.Func([], [IDL.Nat], []),
  'cleanOldNotifications' : IDL.Func([], [IDL.Nat], []),
  'cleanOldOrders' : IDL.Func([], [IDL.Nat], []),
  'countTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
  'createCollege' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [College], []),
  'createNotification' : IDL.Func(
      [UserId, NotificationType, IDL.Text, IDL.Opt(IDL.Text)],
      [Notification],
      [],
    ),
  'deactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
  'deleteApplication' : IDL.Func(
      [AppId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteMessage' : IDL.Func(
      [MessageId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'dryRunSmartCleanup' : IDL.Func([CleanupFilter], [CleanupResult], ['query']),
  'estimatePrice' : IDL.Func(
      [ServiceType, IDL.Bool, IDL.Nat],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'urgency' : IDL.Nat,
          'base' : IDL.Nat,
          'paperCharge' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'forceReassignOrder' : IDL.Func(
      [OrderId, UserId, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'generateAdminIdPreview' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Text],
      ['query'],
    ),
  'getAdminAccount' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getAdminOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getAdminRevenueStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getAllCollegesPricing' : IDL.Func([], [IDL.Vec(CollegePricing)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getApplication' : IDL.Func([AppId], [IDL.Opt(WriterApplication)], []),
  'getCollege' : IDL.Func([CollegeId], [IDL.Opt(College)], []),
  'getCollegePricing' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CollegePricing)],
      ['query'],
    ),
  'getCollegeRevenueStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getMaintenanceLogs' : IDL.Func([], [IDL.Vec(MaintenanceLog)], ['query']),
  'getMaterialPrices' : IDL.Func(
      [],
      [IDL.Record({ 'notebookPrice' : IDL.Nat, 'recordBookPrice' : IDL.Nat })],
      ['query'],
    ),
  'getMyAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], []),
  'getMyCollegePaymentVerifications' : IDL.Func(
      [],
      [IDL.Vec(PaymentVerification)],
      [],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], []),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], []),
  'getMyUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrCreateSessionToken' : IDL.Func([], [IDL.Text], []),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
  'getOrderMessages' : IDL.Func([OrderId], [IDL.Vec(Message)], []),
  'getOrderPayments' : IDL.Func([OrderId], [IDL.Vec(Payment)], []),
  'getOrdersByCollege' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'getOrdersByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'status' : IDL.Text, 'count' : IDL.Nat }))],
      ['query'],
    ),
  'getPaperChargeConfig' : IDL.Func(
      [ServiceType],
      [IDL.Opt(PaperChargeConfig)],
      ['query'],
    ),
  'getPaymentAuditLogs' : IDL.Func([IDL.Nat], [IDL.Vec(PaymentAuditLog)], []),
  'getPaymentLogs' : IDL.Func([], [IDL.Vec(PaymentLog)], ['query']),
  'getPaymentQrBlob' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getPaymentVerification' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentVerification)],
      ['query'],
    ),
  'getPaymentVerifications' : IDL.Func([], [IDL.Vec(PaymentVerification)], []),
  'getPaymentsByOrder' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getRevenueByCollege' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'revenue' : IDL.Nat, 'college' : IDL.Text }))],
      ['query'],
    ),
  'getSystemSettings' : IDL.Func([], [SystemSettings], ['query']),
  'getTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getTransactionDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'recentTransactions' : IDL.Vec(Payment),
          'failedPayments' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'successfulTransactions' : IDL.Nat,
          'pendingVerifications' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([OrderId], [IDL.Nat], ['query']),
  'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(User)], []),
  'getUserBySessionToken' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getWriterApplication' : IDL.Func([AppId], [IDL.Opt(WriterApplication)], []),
  'listAllReassignmentLogs' : IDL.Func([], [IDL.Vec(ReassignmentLog)], []),
  'listApplications' : IDL.Func([], [IDL.Vec(WriterApplication)], ['query']),
  'listCleanupLogs' : IDL.Func([], [IDL.Vec(CleanupLog)], ['query']),
  'listCollegeAdmins' : IDL.Func([CollegeId], [IDL.Vec(UserId)], ['query']),
  'listColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'listPaperChargeConfigs' : IDL.Func(
      [],
      [IDL.Vec(PaperChargeConfig)],
      ['query'],
    ),
  'listReassignmentLogs' : IDL.Func([OrderId], [IDL.Vec(ReassignmentLog)], []),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], []),
  'listWriterApplications' : IDL.Func(
      [],
      [IDL.Vec(WriterApplication)],
      ['query'],
    ),
  'logAction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuditLog], []),
  'loginAsCustomer' : IDL.Func([IDL.Text], [IDL.Opt(User)], []),
  'markMessageRead' : IDL.Func([MessageId], [IDL.Bool], []),
  'markNotificationRead' : IDL.Func([NotifId], [IDL.Bool], []),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        ServiceType,
        IDL.Text,
        Timestamp,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [Order],
      [],
    ),
  'pollPaymentStatus' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'status' : IDL.Text,
          'expiredAt' : IDL.Int,
          'failureReason' : IDL.Opt(IDL.Text),
          'transactionState' : IDL.Text,
          'verifiedAt' : IDL.Opt(IDL.Int),
          'transactionId' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'reassignOrder' : IDL.Func(
      [OrderId, UserId, IDL.Text, IDL.Text],
      [ReassignmentLog],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [UserId],
      [],
    ),
  'rejectApplication' : IDL.Func(
      [AppId, IDL.Text],
      [IDL.Variant({ 'ok' : WriterApplication, 'err' : IDL.Text })],
      [],
    ),
  'rejectPayment' : IDL.Func([PaymentId], [IDL.Bool], []),
  'removeAdminFromCollege' : IDL.Func([CollegeId, UserId], [IDL.Bool], []),
  'runFullCleanup' : IDL.Func(
      [],
      [
        IDL.Record({
          'logsRemoved' : IDL.Nat,
          'ordersRemoved' : IDL.Nat,
          'notifsRemoved' : IDL.Nat,
        }),
      ],
      [],
    ),
  'sendMessage' : IDL.Func(
      [OrderId, IDL.Text, IDL.Vec(IDL.Text)],
      [Message],
      [],
    ),
  'setAllowNewOrders' : IDL.Func([IDL.Bool], [], []),
  'setCollegePricing' : IDL.Func([CollegePricing], [], []),
  'setCustomerCollege' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
  'setMaintenanceEndTime' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'setMaintenanceMessage' : IDL.Func([IDL.Text], [], []),
  'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
  'setMaintenanceReason' : IDL.Func([IDL.Text], [], []),
  'setMaterialPrices' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setPaperChargeConfig' : IDL.Func([PaperChargeUpdate], [IDL.Bool], []),
  'setPaperChargeConfigs' : IDL.Func(
      [IDL.Vec(PaperChargeUpdate)],
      [IDL.Bool],
      [],
    ),
  'setSupportEmail' : IDL.Func([IDL.Text], [], []),
  'setSupportFormUrl' : IDL.Func([IDL.Text], [], []),
  'setWhatsappLink' : IDL.Func([IDL.Text], [], []),
  'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
  'settleOrderPayment' : IDL.Func([OrderId], [IDL.Bool], []),
  'smartCleanup' : IDL.Func([CleanupFilter], [CleanupResult], []),
  'submitPayment' : IDL.Func([OrderId], [Payment], []),
  'submitPaymentRequest' : IDL.Func(
      [OrderId, IDL.Text],
      [IDL.Variant({ 'ok' : Payment, 'err' : IDL.Text })],
      [],
    ),
  'submitWriterApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [WriterApplication],
      [],
    ),
  'updateAdminSkills' : IDL.Func([IDL.Vec(AdminSkill)], [IDL.Bool], []),
  'updateApplicationStatus' : IDL.Func(
      [AppId, ApplicationStatus],
      [IDL.Bool],
      [],
    ),
  'updateCollege' : IDL.Func(
      [CollegeId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateLastLogin' : IDL.Func([], [], []),
  'updateMaintenanceContacts' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  'updatePaymentSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateQrCode' : IDL.Func([IDL.Text], [], []),
  'updateServicePricing' : IDL.Func([IDL.Vec(ServicePriceEntry)], [], []),
  'updateSharePercents' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateSystemSettings' : IDL.Func([SystemSettings], [SystemSettings], []),
  'updateTheme' : IDL.Func([ThemeConfig], [], []),
  'updateUpiId' : IDL.Func([IDL.Text], [], []),
  'updateWebsiteName' : IDL.Func([IDL.Text], [], []),
  'uploadDelivery' : IDL.Func([OrderId, IDL.Vec(IDL.Text)], [IDL.Bool], []),
  'uploadPaymentQr' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'uploadPaymentScreenshot' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'verifyPayment' : IDL.Func([PaymentId], [IDL.Bool], []),
  'verifyPaymentManually' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const OrderId = IDL.Text;
  const CollegeId = IDL.Text;
  const UserId = IDL.Principal;
  const AppId = IDL.Text;
  const ApplicationStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const WriterApplication = IDL.Record({
    'bio' : IDL.Text,
    'status' : ApplicationStatus,
    'appliedAt' : Timestamp,
    'applicantName' : IDL.Text,
    'appId' : AppId,
    'collegeName' : IDL.Text,
    'handwritingUrl' : IDL.Text,
    'reviewNote' : IDL.Text,
    'reviewedBy' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'expertise' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
    'resumeKey' : IDL.Opt(IDL.Text),
    'resumeUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'customer' : IDL.Null,
    'databaseAdmin' : IDL.Null,
    'collegeAdmin' : IDL.Null,
  });
  const College = IDL.Record({
    'adminIds' : IDL.Vec(UserId),
    'collegeCode' : IDL.Text,
    'collegeName' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'adminCount' : IDL.Nat,
    'collegeId' : CollegeId,
    'commissionPercent' : IDL.Nat,
    'adminEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'orderAccepted' : IDL.Null,
    'deliveryUploaded' : IDL.Null,
    'newOrder' : IDL.Null,
    'orderCompleted' : IDL.Null,
    'paymentReceived' : IDL.Null,
    'general' : IDL.Null,
    'orderReassigned' : IDL.Null,
    'revisionRequested' : IDL.Null,
  });
  const NotifId = IDL.Text;
  const Notification = IDL.Record({
    'notifType' : NotificationType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'notifId' : NotifId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  const MessageId = IDL.Text;
  const CallerRole = IDL.Variant({
    'Customer' : IDL.Null,
    'CollegeAdmin' : IDL.Null,
    'DatabaseAdmin' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'ActiveReadyToStart' : IDL.Null,
    'Review' : IDL.Null,
    'Closed' : IDL.Null,
    'PendingPaymentVerification' : IDL.Null,
    'Delivered' : IDL.Null,
    'Correction' : IDL.Null,
    'InProgress' : IDL.Null,
    'Assigned' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const CleanupFilter = IDL.Record({
    'olderThanDays' : IDL.Opt(IDL.Nat),
    'callerRole' : CallerRole,
    'collegeIdFilter' : IDL.Opt(IDL.Text),
    'statusFilter' : IDL.Opt(IDL.Vec(OrderStatus)),
  });
  const CleanupResult = IDL.Record({
    'deletedCount' : IDL.Nat,
    'message' : IDL.Text,
  });
  const ServiceType = IDL.Variant({
    'HardCopy' : IDL.Null,
    'RecordWriting' : IDL.Null,
    'SoftCopy' : IDL.Null,
    'NotesWriting' : IDL.Null,
  });
  const AdminSkill = IDL.Record({
    'skillId' : IDL.Text,
    'skillName' : IDL.Text,
    'isCustom' : IDL.Bool,
  });
  const User = IDL.Record({
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'collegeId' : IDL.Opt(IDL.Text),
    'passwordHash' : IDL.Opt(IDL.Text),
    'lastLogin' : Timestamp,
    'skills' : IDL.Vec(AdminSkill),
    'registeredCollegeId' : IDL.Opt(IDL.Text),
    'mustChangePassword' : IDL.Bool,
  });
  const DeliveryStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'NotDelivered' : IDL.Null,
  });
  const LockStatus = IDL.Variant({
    'Unlocked' : IDL.Null,
    'Locked' : IDL.Null,
  });
  const PaymentSettlementStatus = IDL.Variant({
    'Settled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : OrderStatus,
    'serviceType' : ServiceType,
    'acceptedByAdminName' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'customerPhone' : IDL.Opt(IDL.Text),
    'urgentFlag' : IDL.Bool,
    'urgencyCharge' : IDL.Nat,
    'revenueRecorded' : IDL.Bool,
    'materialChoice' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'materialChargeAmount' : IDL.Nat,
    'acceptedByAdminId' : IDL.Opt(IDL.Text),
    'revisionCount' : IDL.Nat,
    'deliveryStatus' : DeliveryStatus,
    'description' : IDL.Text,
    'fileKeys' : IDL.Vec(IDL.Text),
    'deadline' : Timestamp,
    'orderId' : OrderId,
    'updatedAt' : Timestamp,
    'assignmentLockStatus' : LockStatus,
    'adminMessages' : IDL.Vec(IDL.Text),
    'customCollege' : IDL.Opt(IDL.Text),
    'paperChargeAmount' : IDL.Nat,
    'submissionFiles' : IDL.Vec(IDL.Text),
    'customerId' : UserId,
    'adminId' : IDL.Opt(UserId),
    'paymentSettlementStatus' : PaymentSettlementStatus,
    'acceptedAt' : IDL.Opt(Timestamp),
    'totalPrice' : IDL.Nat,
    'basePrice' : IDL.Nat,
    'college' : IDL.Text,
    'pageCount' : IDL.Nat,
  });
  const LogId = IDL.Text;
  const AuditLog = IDL.Record({
    'resource' : IDL.Text,
    'action' : IDL.Text,
    'logId' : LogId,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'adminId' : UserId,
  });
  const CollegePricing = IDL.Record({
    'urgencyCharge' : IDL.Nat,
    'collegeName' : IDL.Text,
    'hardCopy' : IDL.Nat,
    'otherBase' : IDL.Nat,
    'softCopy' : IDL.Nat,
    'notesWriting' : IDL.Nat,
    'recordWriting' : IDL.Nat,
  });
  const WriterAnalytics = IDL.Record({
    'writerId' : IDL.Principal,
    'completedOrders' : IDL.Nat,
    'assignedOrders' : IDL.Nat,
    'writerName' : IDL.Text,
  });
  const CollegeAnalytics = IDL.Record({
    'totalOrders' : IDL.Nat,
    'collegeName' : IDL.Text,
    'collegeId' : IDL.Text,
    'activeOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const OrderAnalytics = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'completedOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'deliveredOrders' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'writerStats' : IDL.Vec(WriterAnalytics),
    'collegeStats' : IDL.Vec(CollegeAnalytics),
    'totalUsers' : IDL.Nat,
    'orderStats' : OrderAnalytics,
    'totalColleges' : IDL.Nat,
  });
  const MaintenanceLog = IDL.Record({
    'enabledTime' : IDL.Int,
    'enabledBy' : IDL.Text,
    'disabledTime' : IDL.Opt(IDL.Int),
    'reason' : IDL.Text,
    'affectedUsersCount' : IDL.Nat,
  });
  const PaymentVerification = IDL.Record({
    'reviewNotes' : IDL.Opt(IDL.Text),
    'screenshotUrl' : IDL.Opt(IDL.Text),
    'submittedAt' : IDL.Int,
    'reviewedBy' : IDL.Opt(IDL.Text),
    'verificationId' : IDL.Text,
    'reviewTimestamp' : IDL.Opt(IDL.Int),
    'verificationStatus' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TransactionState = IDL.Variant({
    'Failed' : IDL.Null,
    'Refunded' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Processing' : IDL.Null,
    'Created' : IDL.Null,
    'Verified' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentId = IDL.Text;
  const Payment = IDL.Record({
    'status' : PaymentStatus,
    'paymentMethod' : IDL.Text,
    'expiredAt' : IDL.Int,
    'failureReason' : IDL.Opt(IDL.Text),
    'transactionState' : TransactionState,
    'screenshotKey' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'orderId' : OrderId,
    'attemptCount' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'collegeId' : IDL.Text,
    'proofFileKey' : IDL.Opt(IDL.Text),
    'paymentId' : PaymentId,
    'timestamp' : IDL.Int,
    'deviceInfo' : IDL.Opt(IDL.Text),
    'customerId' : UserId,
    'adminId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'verifiedAt' : IDL.Opt(Timestamp),
    'verifiedBy' : IDL.Opt(IDL.Text),
    'ipAddress' : IDL.Opt(IDL.Text),
    'screenshotFileKey' : IDL.Text,
    'transactionId' : IDL.Text,
  });
  const Message = IDL.Record({
    'isDeleted' : IDL.Bool,
    'messageId' : MessageId,
    'text' : IDL.Text,
    'fileKeys' : IDL.Vec(IDL.Text),
    'isRead' : IDL.Bool,
    'orderId' : OrderId,
    'timestamp' : Timestamp,
    'senderName' : IDL.Text,
    'senderRole' : UserRole,
    'senderId' : UserId,
  });
  const PaperChargeConfig = IDL.Record({
    'serviceType' : ServiceType,
    'paperChargePerPage' : IDL.Nat,
    'paperChargeEnabled' : IDL.Bool,
  });
  const PaymentAuditLog = IDL.Record({
    'action' : IDL.Text,
    'actorId' : IDL.Text,
    'orderId' : IDL.Opt(IDL.Text),
    'logId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Opt(IDL.Text),
    'deviceInfo' : IDL.Opt(IDL.Text),
    'amount' : IDL.Opt(IDL.Nat),
    'ipAddress' : IDL.Opt(IDL.Text),
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const PaymentLog = IDL.Record({
    'orderId' : IDL.Text,
    'logId' : IDL.Text,
    'paymentId' : IDL.Text,
    'timestamp' : IDL.Int,
    'customerId' : UserId,
    'adminRemarks' : IDL.Text,
    'reason' : IDL.Text,
  });
  const PaymentSettings = IDL.Record({
    'hasQrBlob' : IDL.Bool,
    'upiId' : IDL.Text,
    'qrCodeKey' : IDL.Text,
    'showQrToUsers' : IDL.Bool,
  });
  const ServicePriceEntry = IDL.Record({
    'serviceType' : ServiceType,
    'urgencyCharge' : IDL.Nat,
    'paperChargePerPage' : IDL.Nat,
    'paperChargeEnabled' : IDL.Bool,
    'basePrice' : IDL.Nat,
  });
  const ThemeConfig = IDL.Record({
    'primaryColor' : IDL.Text,
    'sidebarWidth' : IDL.Nat,
    'accentColor' : IDL.Text,
    'fontFamily' : IDL.Text,
    'sidebarColor' : IDL.Text,
  });
  const SystemSettings = IDL.Record({
    'websiteName' : IDL.Text,
    'qrCodeBlob' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'maintenanceMessage' : IDL.Text,
    'maintenanceEnabledAt' : IDL.Opt(IDL.Int),
    'servicePrices' : IDL.Vec(ServicePriceEntry),
    'emergencySupportEmail' : IDL.Text,
    'whatsappLink' : IDL.Text,
    'supportFormUrl' : IDL.Text,
    'maintenanceLogs' : IDL.Vec(MaintenanceLog),
    'maintenanceMode' : IDL.Bool,
    'notebookPrice' : IDL.Nat,
    'requirePaymentBeforeSubmission' : IDL.Bool,
    'themeConfig' : ThemeConfig,
    'recordBookPrice' : IDL.Nat,
    'whatsappNumber' : IDL.Text,
    'supportEmail' : IDL.Text,
    'upiId' : IDL.Text,
    'qrCodeKey' : IDL.Text,
    'databaseAdminSharePercent' : IDL.Nat,
    'maintenanceEndTime' : IDL.Opt(IDL.Text),
    'showQrToUsers' : IDL.Bool,
    'allowNewOrders' : IDL.Bool,
    'settingsId' : IDL.Text,
    'adminSharePercent' : IDL.Nat,
  });
  const ReassignmentLog = IDL.Record({
    'newAdminId' : UserId,
    'previousAdminName' : IDL.Text,
    'reassignedAt' : Timestamp,
    'reassignedBy' : UserId,
    'orderId' : OrderId,
    'logId' : LogId,
    'previousAdminId' : UserId,
    'newAdminName' : IDL.Text,
    'reason' : IDL.Text,
  });
  const CleanupLog = IDL.Record({
    'cleanupType' : IDL.Text,
    'logId' : LogId,
    'performedAt' : Timestamp,
    'performedBy' : UserId,
    'recordsRemoved' : IDL.Nat,
  });
  const PaperChargeUpdate = IDL.Record({
    'serviceType' : ServiceType,
    'paperChargePerPage' : IDL.Nat,
    'paperChargeEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'acceptOrder' : IDL.Func([OrderId, IDL.Text], [IDL.Bool], []),
    'addAdminToCollege' : IDL.Func([CollegeId, UserId], [IDL.Bool], []),
    'approveApplication' : IDL.Func(
        [AppId, IDL.Text],
        [IDL.Variant({ 'ok' : WriterApplication, 'err' : IDL.Text })],
        [],
      ),
    'assignUserRole' : IDL.Func([UserId, UserRole], [IDL.Bool], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'cleanOldAuditLogs' : IDL.Func([], [IDL.Nat], []),
    'cleanOldNotifications' : IDL.Func([], [IDL.Nat], []),
    'cleanOldOrders' : IDL.Func([], [IDL.Nat], []),
    'countTotalUsers' : IDL.Func([], [IDL.Nat], ['query']),
    'createCollege' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [College], []),
    'createNotification' : IDL.Func(
        [UserId, NotificationType, IDL.Text, IDL.Opt(IDL.Text)],
        [Notification],
        [],
      ),
    'deactivateUser' : IDL.Func([UserId], [IDL.Bool], []),
    'deleteApplication' : IDL.Func(
        [AppId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteMessage' : IDL.Func(
        [MessageId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'dryRunSmartCleanup' : IDL.Func(
        [CleanupFilter],
        [CleanupResult],
        ['query'],
      ),
    'estimatePrice' : IDL.Func(
        [ServiceType, IDL.Bool, IDL.Nat],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'urgency' : IDL.Nat,
            'base' : IDL.Nat,
            'paperCharge' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'forceReassignOrder' : IDL.Func(
        [OrderId, UserId, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'generateAdminIdPreview' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Text],
        ['query'],
      ),
    'getAdminAccount' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getAdminOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getAdminRevenueStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getAllCollegesPricing' : IDL.Func(
        [],
        [IDL.Vec(CollegePricing)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getApplication' : IDL.Func([AppId], [IDL.Opt(WriterApplication)], []),
    'getCollege' : IDL.Func([CollegeId], [IDL.Opt(College)], []),
    'getCollegePricing' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CollegePricing)],
        ['query'],
      ),
    'getCollegeRevenueStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getMaintenanceLogs' : IDL.Func([], [IDL.Vec(MaintenanceLog)], ['query']),
    'getMaterialPrices' : IDL.Func(
        [],
        [
          IDL.Record({
            'notebookPrice' : IDL.Nat,
            'recordBookPrice' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], []),
    'getMyCollegePaymentVerifications' : IDL.Func(
        [],
        [IDL.Vec(PaymentVerification)],
        [],
      ),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], []),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], []),
    'getMyUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrCreateSessionToken' : IDL.Func([], [IDL.Text], []),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
    'getOrderMessages' : IDL.Func([OrderId], [IDL.Vec(Message)], []),
    'getOrderPayments' : IDL.Func([OrderId], [IDL.Vec(Payment)], []),
    'getOrdersByCollege' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'getOrdersByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'status' : IDL.Text, 'count' : IDL.Nat }))],
        ['query'],
      ),
    'getPaperChargeConfig' : IDL.Func(
        [ServiceType],
        [IDL.Opt(PaperChargeConfig)],
        ['query'],
      ),
    'getPaymentAuditLogs' : IDL.Func([IDL.Nat], [IDL.Vec(PaymentAuditLog)], []),
    'getPaymentLogs' : IDL.Func([], [IDL.Vec(PaymentLog)], ['query']),
    'getPaymentQrBlob' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getPaymentVerification' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentVerification)],
        ['query'],
      ),
    'getPaymentVerifications' : IDL.Func(
        [],
        [IDL.Vec(PaymentVerification)],
        [],
      ),
    'getPaymentsByOrder' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getRevenueByCollege' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'revenue' : IDL.Nat, 'college' : IDL.Text }))],
        ['query'],
      ),
    'getSystemSettings' : IDL.Func([], [SystemSettings], ['query']),
    'getTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getTransactionDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'recentTransactions' : IDL.Vec(Payment),
            'failedPayments' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'successfulTransactions' : IDL.Nat,
            'pendingVerifications' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([OrderId], [IDL.Nat], ['query']),
    'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(User)], []),
    'getUserBySessionToken' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getWriterApplication' : IDL.Func(
        [AppId],
        [IDL.Opt(WriterApplication)],
        [],
      ),
    'listAllReassignmentLogs' : IDL.Func([], [IDL.Vec(ReassignmentLog)], []),
    'listApplications' : IDL.Func([], [IDL.Vec(WriterApplication)], ['query']),
    'listCleanupLogs' : IDL.Func([], [IDL.Vec(CleanupLog)], ['query']),
    'listCollegeAdmins' : IDL.Func([CollegeId], [IDL.Vec(UserId)], ['query']),
    'listColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'listPaperChargeConfigs' : IDL.Func(
        [],
        [IDL.Vec(PaperChargeConfig)],
        ['query'],
      ),
    'listReassignmentLogs' : IDL.Func(
        [OrderId],
        [IDL.Vec(ReassignmentLog)],
        [],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], []),
    'listWriterApplications' : IDL.Func(
        [],
        [IDL.Vec(WriterApplication)],
        ['query'],
      ),
    'logAction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [AuditLog], []),
    'loginAsCustomer' : IDL.Func([IDL.Text], [IDL.Opt(User)], []),
    'markMessageRead' : IDL.Func([MessageId], [IDL.Bool], []),
    'markNotificationRead' : IDL.Func([NotifId], [IDL.Bool], []),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          ServiceType,
          IDL.Text,
          Timestamp,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [Order],
        [],
      ),
    'pollPaymentStatus' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'status' : IDL.Text,
            'expiredAt' : IDL.Int,
            'failureReason' : IDL.Opt(IDL.Text),
            'transactionState' : IDL.Text,
            'verifiedAt' : IDL.Opt(IDL.Int),
            'transactionId' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'reassignOrder' : IDL.Func(
        [OrderId, UserId, IDL.Text, IDL.Text],
        [ReassignmentLog],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [UserId],
        [],
      ),
    'rejectApplication' : IDL.Func(
        [AppId, IDL.Text],
        [IDL.Variant({ 'ok' : WriterApplication, 'err' : IDL.Text })],
        [],
      ),
    'rejectPayment' : IDL.Func([PaymentId], [IDL.Bool], []),
    'removeAdminFromCollege' : IDL.Func([CollegeId, UserId], [IDL.Bool], []),
    'runFullCleanup' : IDL.Func(
        [],
        [
          IDL.Record({
            'logsRemoved' : IDL.Nat,
            'ordersRemoved' : IDL.Nat,
            'notifsRemoved' : IDL.Nat,
          }),
        ],
        [],
      ),
    'sendMessage' : IDL.Func(
        [OrderId, IDL.Text, IDL.Vec(IDL.Text)],
        [Message],
        [],
      ),
    'setAllowNewOrders' : IDL.Func([IDL.Bool], [], []),
    'setCollegePricing' : IDL.Func([CollegePricing], [], []),
    'setCustomerCollege' : IDL.Func([UserId, IDL.Text], [IDL.Bool], []),
    'setMaintenanceEndTime' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'setMaintenanceMessage' : IDL.Func([IDL.Text], [], []),
    'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
    'setMaintenanceReason' : IDL.Func([IDL.Text], [], []),
    'setMaterialPrices' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setPaperChargeConfig' : IDL.Func([PaperChargeUpdate], [IDL.Bool], []),
    'setPaperChargeConfigs' : IDL.Func(
        [IDL.Vec(PaperChargeUpdate)],
        [IDL.Bool],
        [],
      ),
    'setSupportEmail' : IDL.Func([IDL.Text], [], []),
    'setSupportFormUrl' : IDL.Func([IDL.Text], [], []),
    'setWhatsappLink' : IDL.Func([IDL.Text], [], []),
    'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
    'settleOrderPayment' : IDL.Func([OrderId], [IDL.Bool], []),
    'smartCleanup' : IDL.Func([CleanupFilter], [CleanupResult], []),
    'submitPayment' : IDL.Func([OrderId], [Payment], []),
    'submitPaymentRequest' : IDL.Func(
        [OrderId, IDL.Text],
        [IDL.Variant({ 'ok' : Payment, 'err' : IDL.Text })],
        [],
      ),
    'submitWriterApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [WriterApplication],
        [],
      ),
    'updateAdminSkills' : IDL.Func([IDL.Vec(AdminSkill)], [IDL.Bool], []),
    'updateApplicationStatus' : IDL.Func(
        [AppId, ApplicationStatus],
        [IDL.Bool],
        [],
      ),
    'updateCollege' : IDL.Func(
        [CollegeId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateLastLogin' : IDL.Func([], [], []),
    'updateMaintenanceContacts' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
    'updatePaymentSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateQrCode' : IDL.Func([IDL.Text], [], []),
    'updateServicePricing' : IDL.Func([IDL.Vec(ServicePriceEntry)], [], []),
    'updateSharePercents' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateSystemSettings' : IDL.Func([SystemSettings], [SystemSettings], []),
    'updateTheme' : IDL.Func([ThemeConfig], [], []),
    'updateUpiId' : IDL.Func([IDL.Text], [], []),
    'updateWebsiteName' : IDL.Func([IDL.Text], [], []),
    'uploadDelivery' : IDL.Func([OrderId, IDL.Vec(IDL.Text)], [IDL.Bool], []),
    'uploadPaymentQr' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'uploadPaymentScreenshot' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'verifyPayment' : IDL.Func([PaymentId], [IDL.Bool], []),
    'verifyPaymentManually' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };